### ISSUE TITLE
Clothes blocking the view of BUY option making UI not good

### ISSUE THREAD

**Issue by aditmehta9** [systers/powerup-android#1389]
## Description
As a user, I need to see the BUY option properly, so that I can see clothes and BUY options properly.

## Mocks
![Screenshot_2020-03-13-13-18-53-889_powerup systers com powerup](https://user-images.githubusercontent.com/35133994/76608453-a2fa2600-653b-11ea-841d-0e131bb88e31.png)
![Screenshot_2020-03-13-13-19-10-082_powerup systers com powerup](https://user-images.githubusercontent.com/35133994/76608464-a7beda00-653b-11ea-9c91-18fa809305d9.png)

### Update [Required]
- [ ] Need to reduce hs_dress_avatar_x.webp length.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by aditmehta9** [comment]
@mayburgos @isabelcosta @sunjunkie @Rimjhim28 Can I work on this issue?

**Comment by HaripriyaB** [comment]
Can I work on this as well? @mayburgos @isabelcosta

**Comment by aditmehta9** [comment]
> 
> 
> Can I work on this as well? @mayburgos @isabelcosta

I have already asked mentors for assigning me this issue. Please ask for another issue.

**Comment by isabelcosta** [comment]
I am not an active maintainer so I don't know what this takes in terms of complexity, but the issue seems appropriate :) @aditmehta9 I will assign this to you since you haven't had a response for so long. Thank you for waiting for approval.

**Comment by aditmehta9** [comment]
@isabelcosta Thanks for assigning. I will start working on it.

**Comment by aditmehta9** [comment]
There is a problem while fixing this issue. If I resize the dress then in the store it is fixed but in avatar dress size is inappropriate. So I want to ask should I use the dress displayed in the store one image and another dress image for the avatar. Or there is another approach please guide me, mentors. I am not tagging any mentors currently because lots of mentors are busy right now. Please guide me whenever you are free.

**Comment by isabelcosta** [comment]
> There is a problem while fixing this issue. If I resize the dress then in the store it is fixed but in avatar dress size is inappropriate. So I want to ask should I use the dress displayed in the store one image and another dress image for the avatar. Or there is another approach please guide me, mentors. I am not tagging any mentors currently because lots of mentors are busy right now. Please guide me whenever you are free.

Right now I don't have an answer for this, but I would advise you to reach out to our Zulip community. What do you think?

**Comment by pknotfound** [comment]
> There is a problem while fixing this issue. If I resize the dress then in the store it is fixed but in avatar dress size is inappropriate. So I want to ask should I use the dress displayed in the store one image and another dress image for the avatar. Or there is another approach please guide me, mentors. I am not tagging any mentors currently because lots of mentors are busy right now. Please guide me whenever you are free.

I think if you use srcCompat that might fix

**Comment by pknotfound** [comment]
> > There is a problem while fixing this issue. If I resize the dress then in the store it is fixed but in avatar dress size is inappropriate. So I want to ask should I use the dress displayed in the store one image and another dress image for the avatar. Or there is another approach please guide me, mentors. I am not tagging any mentors currently because lots of mentors are busy right now. Please guide me whenever you are free.
> 
> I think if you use srcCompat that might fix

It can be used to auto size the image to fit the dimensions
It might help

**Comment by aditmehta9** [comment]
> 
> 
> > There is a problem while fixing this issue. If I resize the dress then in the store it is fixed but in avatar dress size is inappropriate. So I want to ask should I use the dress displayed in the store one image and another dress image for the avatar. Or there is another approach please guide me, mentors. I am not tagging any mentors currently because lots of mentors are busy right now. Please guide me whenever you are free.
> 
> Right now I don't have an answer for this, but I would advise you to reach out to our Zulip community. What do you think?


Sure will do

**Comment by aditmehta9** [comment]
> 
> 
> > > There is a problem while fixing this issue. If I resize the dress then in the store it is fixed but in avatar dress size is inappropriate. So I want to ask should I use the dress displayed in the store one image and another dress image for the avatar. Or there is another approach please guide me, mentors. I am not tagging any mentors currently because lots of mentors are busy right now. Please guide me whenever you are free.
> > 
> > 
> > I think if you use srcCompat that might fix
> 
> It can be used to auto size the image to fit the dimensions
> It might help

Thanks I will do that.

**Comment by aditmehta9** [comment]
> 
> 
> > There is a problem while fixing this issue. If I resize the dress then in the store it is fixed but in avatar dress size is inappropriate. So I want to ask should I use the dress displayed in the store one image and another dress image for the avatar. Or there is another approach please guide me, mentors. I am not tagging any mentors currently because lots of mentors are busy right now. Please guide me whenever you are free.
> 
> I think if you use srcCompat that might fix

No, it won't work that way because images aren't called in the XML file. In addition, srcCompat are resize images runtime. Anyways, thanks for the help.

**Comment by pknotfound** [comment]
> > > There is a problem while fixing this issue. If I resize the dress then in the store it is fixed but in avatar dress size is inappropriate. So I want to ask should I use the dress displayed in the store one image and another dress image for the avatar. Or there is another approach please guide me, mentors. I am not tagging any mentors currently because lots of mentors are busy right now. Please guide me whenever you are free.
> > 
> > 
> > I think if you use srcCompat that might fix
> 
> No, it won't work that way because images aren't called in the XML file. In addition, srcCompat are resize images runtime. Anyways, thanks for the help.

What do you mean by calling XML Files?

**Comment by aditmehta9** [comment]
> 
> 
> > > > There is a problem while fixing this issue. If I resize the dress then in the store it is fixed but in avatar dress size is inappropriate. So I want to ask should I use the dress displayed in the store one image and another dress image for the avatar. Or there is another approach please guide me, mentors. I am not tagging any mentors currently because lots of mentors are busy right now. Please guide me whenever you are free.
> > > 
> > > 
> > > I think if you use srcCompat that might fix
> > 
> > 
> > No, it won't work that way because images aren't called in the XML file. In addition, srcCompat are resize images runtime. Anyways, thanks for the help.
> 
> What do you mean by calling XML Files?

Layout files

**Comment by pknotfound** [comment]
> > > > > There is a problem while fixing this issue. If I resize the dress then in the store it is fixed but in avatar dress size is inappropriate. So I want to ask should I use the dress displayed in the store one image and another dress image for the avatar. Or there is another approach please guide me, mentors. I am not tagging any mentors currently because lots of mentors are busy right now. Please guide me whenever you are free.
> > > > 
> > > > 
> > > > I think if you use srcCompat that might fix
> > > 
> > > 
> > > No, it won't work that way because images aren't called in the XML file. In addition, srcCompat are resize images runtime. Anyways, thanks for the help.
> > 
> > 
> > What do you mean by calling XML Files?
> 
> Layout files

Yes the images are fetched in the XML files, but they are rendered into the XML only.
All you could do is change the particular card in which the images are being rendered.

**Comment by aditmehta9** [comment]
> 
> 
> > > > > > There is a problem while fixing this issue. If I resize the dress then in the store it is fixed but in avatar dress size is inappropriate. So I want to ask should I use the dress displayed in the store one image and another dress image for the avatar. Or there is another approach please guide me, mentors. I am not tagging any mentors currently because lots of mentors are busy right now. Please guide me whenever you are free.
> > > > > 
> > > > > 
> > > > > I think if you use srcCompat that might fix
> > > > 
> > > > 
> > > > No, it won't work that way because images aren't called in the XML file. In addition, srcCompat are resize images runtime. Anyways, thanks for the help.
> > > 
> > > 
> > > What do you mean by calling XML Files?
> > 
> > 
> > Layout files
> 
> Yes the images are fetched in the XML files, but they are rendered into the XML only.
> All you could do is change the particular card in which the images are being rendered.

Yes, I will see it.

**Comment by HaripriyaB** [comment]
Is this issue solved or yet to be solve? @aditmehta9

**Comment by aditmehta9** [comment]
No @HaripriyaB , I am not working on this issue I am trying to work on another issue. Sorry for the inconvenience. I have assigned it to you because you had commented after me.

**Comment by HaripriyaB** [comment]
> 
> 
> No @HaripriyaB , I am not working on this issue I am trying to work on another issue. Sorry for the inconvenience. I have assigned it to you because you had commented after me.

Yup no problem I'll handle it.

**Comment by HaripriyaB** [comment]
I think this issue is no more. I pulled the repo and installed the app and this is what I see. May be the issue is resolved already. @aditmehta9 pls review it.
![Screenshot_2020-05-04-12-38-50-02_edd379f413d28fd43f4496fab0e55864](https://user-images.githubusercontent.com/34762451/80943589-2bdb6280-8e05-11ea-8b57-50b63515022b.png)

**Comment by aditmehta9** [comment]
> 
> 
> I think this issue is no more. I pulled the repo and installed the app and this is what I see. May be the issue is resolved already. @aditmehta9 pls review it.
> ![Screenshot_2020-05-04-12-38-50-02_edd379f413d28fd43f4496fab0e55864](https://user-images.githubusercontent.com/34762451/80943589-2bdb6280-8e05-11ea-8b57-50b63515022b.png)

No, the problem still persists. Level 1 images were ok. It was problem for level to avatar shop. Please check level 2 avatar shop @HaripriyaB

**Comment by HaripriyaB** [comment]
Yes @aditmehta9 The problem is in the level 2 of the game. So I'll work on it.
![Screenshot_2020-05-04-12-56-17-88_edd379f413d28fd43f4496fab0e55864](https://user-images.githubusercontent.com/34762451/80944324-e4ee6c80-8e06-11ea-9e9a-7df9fe9bcaf8.png)
